/* 
Topic : Even Fibonacci numbers
Problem Statement : Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
                        By starting with 1 and 2, the first 10 terms will be:
 */