"""
    Topic : Even Fibonacci numbers
    Problem Statement : Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
                        By starting with 1 and 2, the first 10 terms will be:
"""

def fibonacci_range(end_point):
    a, b = 1, 2
    while True:
        yield a
        a, b = b, a+b
        if a >= end_point:
            break

result = sum([x for x in fibonacci_range(4000000) if x % 2 == 0])
print(result)